############# Render Config Settings ##############

[RenderConfig]
FileTop = """
    // Whatever you put in this `FileTop` section will end up 
    // being printed at the top of every generated code file.
    """
# AutoExpandedVars = ""
# VariableDeclarations = ""
# DefaultVarExpTemplate = ""
# DefaultFuncExpTemplate = ""
# DefaultAnyExpTemplate = ""
# TriggerMap = ""

[RenderConfig.C]
# HFileTop = ""
# HFileIncludes = "#include <stdio.h>"
# CFileIncludes = "#include <stdlib.h>"
# CFileTop = ""
# CFileExtension = ".inc"
# HFileExtension = ".hpp"
# CEnumDeclarer = ""

[RenderConfig.CSharp]
# NameSpace = ""
# Usings = ""
# ClassCode = ""
# BaseList = "MyUserBaseClass, IMyOtherUserInterface"
# UseNullable = false
# UsePartialClass = false

[RenderConfig.JavaScript]
# ClassCode = ""
# ExtendsSuperClass = "MyUserBaseClass"
# UseExportOnClass = true
# PrivatePrefix = "_"

############# SmRunner.Settings ###############

[SmRunnerSettings]
# outputDirectory = "./gen"
# outputCodeGenTimestamp = true
# outputStateSmithVersionInfo = false
# propagateExceptions = true
# dumpErrorsToFile = true

[SmRunnerSettings.smDesignDescriber]
# enabled = true
# outputDirectory = ".."
# outputAncestorHandlers = true

[SmRunnerSettings.smDesignDescriber.outputSections]
# beforeTransformations = false
# afterTransformations  = true

[SmRunnerSettings.algoBalanced1]
# outputEventIdToStringFunction = false
# outputStateIdToStringFunction = false

[SmRunnerSettings.simulation]
enableGeneration = true
# outputDirectory = ".."
# outputFileNamePostfix = ".sim.html"

# There are more SmRunnerSettings. See C# classes on github project.
# TODO link: 