############# Render Config Settings ##############

[RenderConfig]
FileTop = """
    // Whatever you put in this `FileTop` section
    // will end up being printed at the top of every file
    """
AutoExpandedVars = "<string-none>"
VariableDeclarations = "<string-none>"
DefaultVarExpTemplate = "<string-none>"
DefaultFuncExpTemplate = "<string-none>"
DefaultAnyExpTemplate = "<string-none>"
TriggerMap = "<string-none>"

[RenderConfig.C]
HFileTop = "<string-none>"
HFileIncludes = "<string-none>"
CFileIncludes = "<string-none>"
CFileTop = "<string-none>"
CFileExtension = "<string-none>"
HFileExtension = "<string-none>"
CEnumDeclarer = "<string-none>"

[RenderConfig.CSharp]
NameSpace = "<string-none>"
Usings = "<string-none>"
ClassCode = "<string-none>"
BaseList = "<string-none>"
UseNullable = "<bool-none>"
UsePartialClass = "<bool-none>"


############# SmRunner.Settings ###############

[SmRunnerSettings]
outputDirectory = "<string-none>"
outputCodeGenTimestamp = "<bool-none>"
outputStateSmithVersionInfo = "<bool-none>"
propagateExceptions = "<bool-none>"
dumpErrorsToFile = "<bool-none>"

[SmRunnerSettings.smDesignDescriber]
enabled = "<bool-none>"
outputDirectory = "<string-none>"
outputAncestorHandlers = "<bool-none>"

[SmRunnerSettings.smDesignDescriber.outputSections]
beforeTransformations = "<bool-none>"
afterTransformations  = "<bool-none>"

[SmRunnerSettings.algoBalanced1]
outputEventIdToStringFunction = "<bool-none>"
outputStateIdToStringFunction = "<bool-none>"

[SmRunnerSettings.simulation]
enableGeneration = "<bool-none>"
outputDirectory = "<string-none>"
outputFileNamePostfix = "<string-none>"

# There are more SmRunnerSettings. See C# classes on github project.